name: "[build] flatpak bundle"

on:
  release:
    types:
      - created

jobs:
  flatpak-validation: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: "Validate build"
        uses: ./.github/workflows/flatpak-ci.yml

  flatpak-bundle:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Flatpak bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          build-bundle: true
          upload-artifact: true
          manifest-path: flatpak/io.github.andrepg.Doit.json
          bundle: io.github.andrepg.Doit-${{ github.ref_name }}.flatpak
          cache-key: flatpak-release-${{ github.ref_name }}

  finish-release:
    runs-on: ubuntu-latest
    needs: 
      - flatpak-validation
      - flatpak-bundle
    
    steps:
        - name: Publish release (remove draft)
          uses: softprops/action-gh-release@v2
          with:
            draft: false
